version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD : 'mahmudinproject'
      MYSQL_DATABASE : 'daihatsu_service_queue'
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db-networks
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD : 'mahmudinproject'
      PMA_PORT : '3306'
    networks:
      - db-networks
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - db-networks

volumes:
  mysql:

networks:
  db-networks:
    name: db-networks
    attachable: true
  
